;;; Sierra Script 1.0 - (do not remove this comment)
;
; * SCI Game Header
; * By Brian Provinciano
; *************************************************************************
; * Put all the defines specific to your game in here

; Base Scripts
(define MAIN_SCRIPT 0)
(define DOOR_SCRIPT 974)
(define AUTODOOR_SCRIPT 975)
(define INITROOMS_SCRIPT 976)
(define DYING_SCRIPT 977)
(define DISPOSELOAD_SCRIPT 978)
(define CONTROLS_SCRIPT 979)
(define DPATH_SCRIPT 980)
(define DCICON_SCRIPT 981)
(define REV_SCRIPT 982)
(define WANDER_SCRIPT 983)
(define FOLLOW_SCRIPT 984)
(define TIMER_SCRIPT 985)
(define WINDOW_SCRIPT 986)
(define GAUGE_SCRIPT 987)
(define EXTRA_SCRIPT 988)
(define SOUND_SCRIPT 989)
(define SYSWINDOW_SCRIPT 990)
(define JUMP_SCRIPT 991)
(define CYCLE_SCRIPT 992)
(define FILEIO_SCRIPT 993)
(define GAME_SCRIPT 994)
(define INVENTORY_SCRIPT 995)
(define USER_SCRIPT 996)
(define MENUBAR_SCRIPT 997)
(define FEATURE_SCRIPT 998)
(define OBJ_SCRIPT 999)
; Game Scripts
(define TITLESCREEN_SCRIPT 800)
; Defaults
(define NORMAL_SPEED 8)
; Sounds
(define DUMMY_SOUND 1)
(define SCORE_SOUND 900)
(define DEATH_SOUND 2)
; Inventory Items
(define INV_NOTHING 0)
(define INV_KIT 1)
(define INV_SHOVEL 2)
(define INV_METAL_BAR 3)
(define INV_KITE 4)
(define INV_MEAT 5)
(define INV_LETTER 6)
(define INV_MAP 7)
(define INV_BLOW_DART_GUN 8)
(define INV_MARBLES 9)
(define INV_GOGGLES 10)
(define INV_MAGNET 11)
(define INV_EXPLOSIVE 12)
(define INV_BLOCK 13)
(define INV_RULER 14)
(define INV_BOW 15)
(define INV_ARROW 16)
(define INV_ACORN 17)
(define INV_RING 18)
(define INV_PACKAGE 19)
(define INV_BOOKS 20)
(define INV_FLOWER 21)
(define INV_POTION 22)
(define INV_TITANITE 23)
(define INV_LETTER2 24)
(define INV_GLIDER 25)
(define INV_KEY 26)
(define INV_ARMOR 27)
; Fonts
(define DEFAULT_FONT 0)
(define WINDOW_FONT 1)
(define SMALL_FONT 4)
(define LARGE_FONT 9)
(define DEBUG_FONT 999)
; Menu IDs eg. $302 means third menu, second item
(define MENU_ABOUT $0101)
(define MENU_HELP $0102)
(define MENU_DIFFICULTY $0103)
(define MENU_RESTART $0201)
(define MENU_SAVE $0202)
(define MENU_RESTORE $0203)
(define MENU_QUIT $0205)
(define MENU_ASKABOUT $0301)
(define MENU_RETYPE $0302)
(define MENU_INVENTORY $0304)
(define MENU_CHARACTER $0305)
(define MENU_NOTES $0306)
(define MENU_CHANGESPEED $0401)
(define MENU_FASTERSPEED $0403)
(define MENU_NORMALSPEED $0404)
(define MENU_SLOWERSPEED $0405)
(define MENU_VOLUME $0501)
(define MENU_TOGGLESOUND $0502)
